### ISSUE TITLE
2015-12-04 review

### ISSUE THREAD

**Issue by mfulton26** [FormulaTranslator/AdventOfCode2015#5]
# Review

## `string.startsWith`

```patch
diff --git a/Project4_2015.py b/Project4_2015.py
index 923f3b1..0e9d320 100644
--- a/Project4_2015.py
+++ b/Project4_2015.py
@@ -8,22 +8,9 @@ while not match_found:
     secret_code = project_input + str(number_to_add)
     hash_result = hashlib.md5(secret_code.encode())
     hex_result = hash_result.hexdigest()
-    for index, char in enumerate(hex_result):
-        if char != '0' and index == 0:
-            break
-        elif char != '0' and index == 1:
-            break
-        elif char != '0' and index == 2:
-            break
-        elif char != '0' and index == 3:
-            break
-        elif char != '0' and index == 4:
-            break
-        elif char != '0' and index == 5:
-            break
-        elif index == 5:
-            print(number_to_add)
-            print(hex_result)
-            match_found = True
+    if hex_result.startswith('000000'):
+        print(number_to_add)
+        print(hex_result)
+        match_found = True

     number_to_add += 1
```

## `from X import Y`

if you're only use one thing from a module you can import it directly (there's probably some syntax for importing multiple specific things too); this could result in name conflicts though

```patch
diff --git a/Project4_2015.py b/Project4_2015.py
--- a/Project4_2015.py
+++ b/Project4_2015.py
@@ -1,4 +1,4 @@
-import hashlib
+import md5 from hashlib

 project_input = 'yzbqklnj'
 number_to_add = 0
@@ -6,7 +6,7 @@ match_found = False

 while not match_found:
     secret_code = project_input + str(number_to_add)
-    hash_result = hashlib.md5(secret_code.encode())
+    hash_result = md5(secret_code.encode())
     hex_result = hash_result.hexdigest()
     if hex_result.startswith('000000'):
         print(number_to_add)
```

## `break` as an alternative to "found" flag

personally I try to avoid top-level, stateful variables

```patch
diff --git a/Project4_2015.py b/Project4_2015.py
--- a/Project4_2015.py
+++ b/Project4_2015.py
@@ -2,15 +2,14 @@ from hashlib import md5

 project_input = 'yzbqklnj'
 number_to_add = 0
-match_found = False

-while not match_found:
+while True:
     secret_code = project_input + str(number_to_add)
     hash_result = md5(secret_code.encode())
     hex_result = hash_result.hexdigest()
     if hex_result.startswith('000000'):
         print(number_to_add)
         print(hex_result)
-        match_found = True
+        break

     number_to_add += 1
```

## `itertools.count`

I know you talked about trying not to use modules but some things are just so basic to any Python program so you might want to use some :smile:

```patch
diff --git a/Project4_2015.py b/Project4_2015.py
--- a/Project4_2015.py
+++ b/Project4_2015.py
@@ -1,9 +1,9 @@
+from itertools import count
 from hashlib import md5

 project_input = 'yzbqklnj'
-number_to_add = 0

-while True:
+for number_to_add in count():
     secret_code = project_input + str(number_to_add)
     hash_result = md5(secret_code.encode())
     hex_result = hash_result.hexdigest()
@@ -11,5 +11,3 @@ while True:
         print(number_to_add)
         print(hex_result)
         break
-
-    number_to_add += 1
```

## continuing work to next answer

as this solution builds (literally) on-top of the solution for part 1 you could actually print both as you go

```patch
diff --git a/Project4_2015.py b/Project4_2015.py
--- a/Project4_2015.py
+++ b/Project4_2015.py
@@ -2,12 +2,14 @@ from itertools import count
 from hashlib import md5

 project_input = 'yzbqklnj'
+numbers_to_add = count()

-for number_to_add in count():
-    secret_code = project_input + str(number_to_add)
-    hash_result = md5(secret_code.encode())
-    hex_result = hash_result.hexdigest()
-    if hex_result.startswith('000000'):
-        print(number_to_add)
-        print(hex_result)
-        break
+for prefix in ['00000', '000000']:
+    for number_to_add in numbers_to_add:
+        secret_code = project_input + str(number_to_add)
+        hash_result = md5(secret_code.encode())
+        hex_result = hash_result.hexdigest()
+        if hex_result.startswith(prefix):
+            print(number_to_add)
+            print(hex_result)
+            break

```

## decoupling output code from solving code

personally I like to decouple I/O from functions as sometimes you'll want to use a function and print its results while other times you'll want to actually take those results and do something else with them instead of printing them directly

you could build a list of answers and return it but I find using `yield` makes streamable code that scales (while a list as it grows in size requires more memory but a stream only uses however much memory a single element in the stream requires)

```patch
diff --git a/Project4_2015.py b/Project4_2015.py
--- a/Project4_2015.py
+++ b/Project4_2015.py
@@ -1,15 +1,18 @@
 from itertools import count
 from hashlib import md5

-project_input = 'yzbqklnj'
-numbers_to_add = count()
-
-for prefix in ['00000', '000000']:
-    for number_to_add in numbers_to_add:
-        secret_code = project_input + str(number_to_add)
-        hash_result = md5(secret_code.encode())
-        hex_result = hash_result.hexdigest()
-        if hex_result.startswith(prefix):
-            print(number_to_add)
-            print(hex_result)
-            break
+
+def solve(input, numbers_to_add=count(), prefixes=['00000', '000000']):
+    for prefix in prefixes:
+        for number_to_add in numbers_to_add:
+            secret_code = input + str(number_to_add)
+            hash_result = md5(secret_code.encode())
+            hex_result = hash_result.hexdigest()
+            if hex_result.startswith(prefix):
+                yield (number_to_add, hex_result)
+                break
+
+
+for (number_to_add, hex_result) in solve('yzbqklnj'):
+    print(number_to_add)
+    print(hex_result)
```

**Comment by FormulaTranslator** [comment]
This is great, thanks! I think I'm going to keep with the simpler stuff. That yield concept is cool though.
Also, is there a fundamental reason why importing count is better than actually counting? They seem like the same thing, one uses a while loop and the other a for loop.

**Comment by mfulton26** [comment]
I think `itertools.count()` lets you clearly loop with an incrementing variable while with the `while` loop you could theoretically do _anything_ with your "count" variable (e.g. `number_to_add += 3`)

pros:
- simpler?
- consistency? (there are tons of cool, helpful things in `itertools` and it is very pythonic to use them I think)

cons:
- less flexible (but then there are more complex, tested iterators in `itertools` that compensates for this)

**Comment by mfulton26** [comment]
plus I've seen people forget to increment their count variables before :smile:

**Comment by FormulaTranslator** [comment]
lol that's awesome. Thanks!

**Comment by FormulaTranslator** [comment]
Thoughts on this bit of code:

from itertools import count

def solve(password, *args):
    numbers_to_add = count()
    for prefix in args:
        for number_to_add in numbers_to_add:
            secret_code = password + str(number_to_add)
            hash_result = md5(secret_code.encode())
            hex_result = hash_result.hexdigest()
            if hex_result.startswith(prefix):
                yield number_to_add, hex_result
                break

password_vars = solve('yzbqklnj', '00000', '000000')
print(*password_vars, sep='\n')

**Comment by FormulaTranslator** [comment]
Sorry, it took out the tabs...I'm not an expert on this thing yet

**Comment by mfulton26** [comment]
That looks great to me. One thing to note, using `*args` limits you from later adding additional parameters to your function signature; I think we can have confidence that that is fine as it is extremely unlikely that more will be needed, but just something to note as to why you may not see `*args` not used more often than it is (sometimes a single argument that is list is more flexible for iterating on the code in the future).

For formatting you may like https://guides.github.com/features/mastering-markdown/ 😄 

Other than indentation and and `md5` import (which I'm sure you have) I think the only thing I would suggest changing is the name of `args`:

```python
from itertools import count
from hashlib import md5


def solve(password, *prefixes):
    numbers_to_add = count()
    for prefix in prefixes:
        for number_to_add in numbers_to_add:
            secret_code = password + str(number_to_add)
            hash_result = md5(secret_code.encode())
            hex_result = hash_result.hexdigest()
            if hex_result.startswith(prefix):
                yield number_to_add, hex_result
                break


password_vars = solve('yzbqklnj', '00000', '000000')
print(*password_vars, sep='\n')

```

P.S. I didn't know you could do that with `print` with `sep`; I like it!

**Comment by FormulaTranslator** [comment]
What about this?  ***EDIT:*** I tried this first and it works. Then after looking at it, I agree that a single list argument is better than *args. *args is not required and in theory the  code could be run without it (like if someone forgot to put the arguments in). The list would be best because it would require the input. Thanks!

```python
from itertools import count
from hashlib import md5


def solve(password, *prefixes):
    numbers_to_add = count()
    for prefix in prefixes:
        for number_to_add in numbers_to_add:
            secret_code = password + str(number_to_add)
            hash_result = md5(secret_code.encode())
            hex_result = hash_result.hexdigest()
            if hex_result.startswith(prefix):
                yield number_to_add, hex_result
                break


password_requirements = ['00000', '000000']
password_vars = solve('yzbqklnj', *password_requirements)
print(*password_vars, sep='\n')
```
